apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: manivannancsmca/kafka-producer:4e2bc24cd6c1cdba6c55047d02fb6a67e1a4c69c

        ports:
        - containerPort: 8080

        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-headless.kube-system.svc.cluster.local:9092"

        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: kafka-producer
  ports:
    - name: http
      port: 80         # The port the Load Balancer exposes externally
      targetPort: 8080 # The port your Spring Boot/Java app listens on inside the container
      protocol: TCP
